# Generated by Django 3.0.6 on 2020-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
