# Generated by Django 3.0.7 on 2020-06-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='name',
            field=models.CharField(default=44, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_data',
            name='password',
            field=models.CharField(default=555, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_data',
            name='phone_number',
            field=models.CharField(default=5656, max_length=11),
            preserve_default=False,
        ),
    ]
