# Generated by Django 3.0.3 on 2020-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('allowedArea', models.CharField(max_length=100)),
            ],
        ),
    ]
