# Generated by Django 3.0.3 on 2020-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_business', '0003_businessdata_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='start_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
