# Generated by Django 3.0.3 on 2020-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_business', '0004_auto_20200620_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdata',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
